name: mark_with_label
description: With that package you will be able to use Marker With Label API for Google Maps JavaScript API from Dart scripts.
version: 0.0.2
homepage: https://github.com/olimou/dart-markerwithlabel
author: Emerson Moura <olimou@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  js_wrapping: ^0.4.0
  google_maps: ">=3.0.0 <4.0.0"

dev_dependencies:
  js_wrapping_generator: ^0.4.0
  test: ^0.12.0
